# Generated by Django 5.0.6 on 2026-09-29 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='本のタイトル')),
                ('author', models.CharField(max_length=100, verbose_name='著者名')),
                ('rating', models.IntegerField(default=3, verbose_name='評価(1~5)')),
                ('review', models.TextField(blank=True, verbose_name='感想')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='登録日時')),
            ],
        ),
    ]
