# Generated by Django 5.0.6 on 2026-09-25 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cafe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='店名')),
                ('area', models.CharField(max_length=100, verbose_name='エリア')),
                ('genre', models.CharField(blank=True, max_length=100, null=True, verbose_name='ジャンル')),
                ('rating', models.IntegerField(default=3, verbose_name='評価(1~5)')),
                ('recommend_menu', models.CharField(max_length=100, verbose_name='おすすめメニュー')),
                ('memo', models.TextField(blank=True, null=True, verbose_name='感想、メモ')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='登録日時')),
            ],
        ),
    ]
